_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
architecture:
    value: GramNet-genimage-sdv1.4
batch_size:
    value: 64
blur_prob:
    value: 0.1
crop_size:
    value: 224
dataset:
    value: genimage-sdv1.4-jpeg-aligned
detect_method:
    value: Gram
epochs:
    value: 30
jpg_prob:
    value: 0.1
learning_rate:
    value: 0.0001
